name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0

      - name: Run ESLint
        run: npx eslint ./thisCodeGetsTested
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
        continue-on-error: false



