name: Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
#    - run: semgrep --error ./thisCodeGetsTested -f semgrepRules.yml
#Will man das Dashboard (www.semgrep.dev) nicht nutzen, kann man letzteren Befehl verwenden
#um die Regeln manuell einzubinden. Die error flag bedingt das die Pipeline bei einem Fund abbricht.
